const fs = require("node:fs");
const path = require("node:path");
const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
} = require("expo/config-plugins");

/**
 * Android Auto Backup rules for Pixy.
 *
 * Only the `database` domain is backed up. AsyncStorage keeps every log,
 * tag, and setting in one SQLite database (`RKStorage`), so that domain is
 * exactly the user's data and nothing else: no PostHog queue, no Sentry
 * envelopes, no cached files. Move storage out of AsyncStorage and these
 * rules must follow, or Auto Backup silently stops covering user data.
 *
 * `requireFlags="clientSideEncryption"` and
 * `disableIfNoEncryptionCapabilities="true"` keep mood data off Google's
 * servers unless the phone has a screen lock, because Android derives the
 * backup key from it (Android 9 and newer). Device-to-device transfer is
 * allowed without a cloud account. The backup agent adds the user's switch
 * and records the last cloud backup. See docs/backup.md.
 */
const BACKUP_RULES_NAME = "pixy_backup_rules";
/** Backup agent from `modules/pixy-mood-tracker-backup`: skips Pixy when the user turns backup off. */
const BACKUP_AGENT = "expo.modules.pixymoodtrackerbackup.PixyBackupAgent";
const DATA_EXTRACTION_RULES_NAME = "pixy_data_extraction_rules";

/** `res/xml/pixy_backup_rules.xml`, read on Android 11 and lower. */
const BACKUP_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js. Edit the plugin, not this file. -->
<full-backup-content>
  <include domain="database" path="." requireFlags="clientSideEncryption" />
</full-backup-content>
`;

/** `res/xml/pixy_data_extraction_rules.xml`, read on Android 12 and higher. */
const DATA_EXTRACTION_RULES_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withAndroidBackupRules.js. Edit the plugin, not this file. -->
<data-extraction-rules>
  <cloud-backup disableIfNoEncryptionCapabilities="true">
    <include domain="database" path="." />
  </cloud-backup>
  <device-transfer>
    <include domain="database" path="." />
  </device-transfer>
</data-extraction-rules>
`;

/**
 * Points the `<application>` element at the two rule files and the backup
 * agent, and turns Auto Backup on. `fullBackupOnly` keeps Auto Backup with a
 * custom agent. Returns the same manifest object.
 */
const applyBackupManifestAttributes = (androidManifest) => {
  const application =
    AndroidConfig.Manifest.getMainApplicationOrThrow(androidManifest);
  application.$["android:allowBackup"] = "true";
  application.$["android:backupAgent"] = BACKUP_AGENT;
  application.$["android:fullBackupOnly"] = "true";
  application.$["android:fullBackupContent"] = `@xml/${BACKUP_RULES_NAME}`;
  application.$["android:dataExtractionRules"] =
    `@xml/${DATA_EXTRACTION_RULES_NAME}`;
  return androidManifest;
};

/** Writes both rule files into `android/app/src/main/res/xml/`. */
const writeBackupRuleFiles = (resourceDirectory) => {
  const xmlDirectory = path.join(resourceDirectory, "xml");
  fs.mkdirSync(xmlDirectory, { recursive: true });
  fs.writeFileSync(
    path.join(xmlDirectory, `${BACKUP_RULES_NAME}.xml`),
    BACKUP_RULES_XML
  );
  fs.writeFileSync(
    path.join(xmlDirectory, `${DATA_EXTRACTION_RULES_NAME}.xml`),
    DATA_EXTRACTION_RULES_XML
  );
};

/** Expo config plugin: Android Auto Backup limited to the AsyncStorage database. */
const withAndroidBackupRules = (config) => {
  const withManifest = withAndroidManifest(config, (manifestConfig) => {
    manifestConfig.modResults = applyBackupManifestAttributes(
      manifestConfig.modResults
    );
    return manifestConfig;
  });

  return withDangerousMod(withManifest, [
    "android",
    async (modConfig) => {
      const resourceDirectory =
        await AndroidConfig.Paths.getResourceFolderAsync(
          modConfig.modRequest.projectRoot
        );
      writeBackupRuleFiles(resourceDirectory);
      return modConfig;
    },
  ]);
};

module.exports = withAndroidBackupRules;
module.exports.applyBackupManifestAttributes = applyBackupManifestAttributes;
module.exports.writeBackupRuleFiles = writeBackupRuleFiles;
module.exports.BACKUP_RULES_XML = BACKUP_RULES_XML;
module.exports.DATA_EXTRACTION_RULES_XML = DATA_EXTRACTION_RULES_XML;
